services:
  postgres:
    image: postgres:17-alpine
    container_name: cinema-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
    volumes:
      - cinema-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U postgres -d cinema"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - cinema-redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  cinema-pgdata:
  cinema-redisdata: